name: CI

on: push

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    
    env:
      COVERITY_DIRECTORY: ~/coverity_analysis_linux

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Compile Test and Verify
        run: mvn clean verify
          
      - name: Download Coverity
        if: hashFiles('$COVERITY_DIRECTORY/VERSION.xml) == ''
        run: wget https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=rlp_01" -O ~/coverity_tool.tgz && tar zxvf ~/coverity_tool.tgz -C $COVERITY_DIRECTORY
        
      - name: Cache Coverity
        uses: actions/cache@v2
        with:
          path: ~/coverity_analysis_linux
          key: ${{ runner.os }}-coverity-${{ hashFiles('$COVERITY_DIRECTORY/VERSION.xml') }}
          restore-keys: ${{ runner.os }}-coverity-
